[tool.cibuildwheel]
test-command = "python {project}/test.py"

[tool.cibuildwheel.linux]
# Only build CPython (no PyPy) on x86_64 architecture
build = "cp*x86_64"
before-all = [
    # Install Zig on CentOS
    "cd /tmp",
    "curl -O https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz",
    "tar xf zig-linux-x86_64-0.9.1.tar.xz",
    "mv zig-linux-x86_64-0.9.1 /usr/local/bin/zig-linux-0.9.1"
]
environment = { PATH="$PATH:/usr/local/bin/zig-linux-0.9.1" }

[tool.cibuildwheel.macos]
# Only build CPython (no PyPy) on x86_64 architecture
build = "cp*x86_64"
before-all = [
    # Install Zig on MacOS
    "cd /tmp",
    "curl -O https://ziglang.org/download/0.9.1/zig-macos-x86_64-0.9.1.tar.xz",
    "tar xf zig-macos-x86_64-0.9.1.tar.xz",
    "mv zig-macos-x86_64-0.9.1 /usr/local/bin/zig-macos-0.9.1"
]
environment = { PATH="$PATH:/usr/local/bin/zig-macos-0.9.1" }
before-test = "python -sSc 'import platform; print(platform.machine())'"
