[tool.cibuildwheel.linux]
# Only build CPython (no PyPy) on x86_64 architecture
build = "cp*x86_64"
before-all = [
    # Install Zig on CentOS
    "cd /tmp",
    "curl -O https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz",
    "tar xf zig-linux-x86_64-0.9.1.tar.xz",
    "mv zig-linux-x86_64-0.9.1 /usr/local/bin/zig-linux-0.9.1"
]
environment = { PATH="$PATH:/usr/local/bin/zig-linux-0.9.1" }
test-command = 'python -c "import zaml; assert zaml.load() == 1"'
