name: CI
on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Run tests
        run: python test.py