name: Build

on: pull_request

jobs:
  build_linux_wheels:
    name: Build wheels on linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_SOME_OPTION: value

  build_macos_wheels:
    name: Build wheels on macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_SOME_OPTION: value

  build_windows_wheels:
    name: Build wheels on Windows
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_SOME_OPTION: value